### ISSUE TITLE
CUDA, Cupy error ! 

### ISSUE THREAD

**Issue by phongnhhn92** [KAIST-VCLAB/sphere-stereo#6]
Hi,

Thanks for the code ! I am trying ourt your code on the provided testing data and I have this error. Can you help to take a look ? 

master ~/sphere-stereo python python/main.py --dataset_path evaluation_dataset --references_indices 0 2 --evaluate True
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/sphere-stereo/python/main.py", line 84, in <module>
    rgbd_estimator = RGBD_Estimator(calibrations, args.min_dist, args.max_dist, args.candidate_count,
  File "/teamspace/studios/this_studio/sphere-stereo/python/depth_estimation.py", line 72, in __init__
    self.cost_filter = ISB_Filter(candidate_count, matching_resolution, device)
  File "/teamspace/studios/this_studio/sphere-stereo/python/isb_filter.py", line 54, in __init__
    self.guide_downsample_cuda = module.get_function("guideDownsample2xKernel")
  File "cupy/_core/raw.pyx", line 487, in cupy._core.raw.RawModule.get_function
  File "cupy/_core/raw.pyx", line 100, in cupy._core.raw.RawKernel.kernel.__get__
  File "cupy/_core/raw.pyx", line 117, in cupy._core.raw.RawKernel._kernel
  File "cupy/_util.pyx", line 64, in cupy._util.memoize.decorator.ret
  File "cupy/_core/raw.pyx", line 538, in cupy._core.raw._get_raw_module
  File "cupy/_core/core.pyx", line 2236, in cupy._core.core.compile_with_cache
  File "cupy/_core/core.pyx", line 2254, in cupy._core.core.compile_with_cache
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 484, in _compile_module_with_cache
    return _compile_with_cache_cuda(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 562, in _compile_with_cache_cuda
    ptx, mapping = compile_using_nvrtc(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/cupy/cuda/compiler.py", line 317, in compile_using_nvrtc
    cu_file.write(source)
UnicodeEncodeError: 'ascii' codec can't encode character '\u201c' in position 1438: ordinal not in range(128)

**Comment by thesilencelies** [comment]
@phongnhhn92 a little late, but for some reason the code has weird quotation marks inside the license text. If you ctrl-f for the offending characters (you can find it in the file or use the unicode above) and replace it with something in the ascii range then it should work

**Comment by phongnhhn92** [comment]
Hi @thesilencelies 

I wonder where should I search for this character '\u201c'. Is this gonna be in this file: https://github.com/KAIST-VCLAB/sphere-stereo/blob/b4bd39572845783a3a06c333e0c077ad15e2fba2/python/isb_filter.cu

I have try to find it but no results found. In fact I search your whole repo and found none of it :(

**Comment by thesilencelies** [comment]
@phongnhhn92 it's the quotation marks for the legal stuff. If you delete that whole comment at the top (the license bit) I think the parser should stop choking on it. You can't distribute the code like that though.

**Comment by phongnhhn92** [comment]
Thanks ! It works for me
